<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.MultiTenancy.EntityFrameworkCore</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Aiel.EntityFrameworkCore\Aiel.EntityFrameworkCore.csproj" />
      <ProjectReference Include="..\Aiel.MultiTenancy\Aiel.MultiTenancy.csproj" />
    </ItemGroup>

</Project>
