<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.AspNetCore.Logging</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aiel.Logging.Abstractions\Aiel.Logging.Abstractions.csproj" />
    </ItemGroup>

</Project>
