<Project>

    <!-- Shared defaults and language settings -->
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NeutralLanguage>en</NeutralLanguage>

        <IsAotCompatible>false</IsAotCompatible>
        <IsTrimmable>false</IsTrimmable>

        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <!-- NBGV versioning -->
        <NBGV_ThisAssemblyNamespace>$(AssemblyName)</NBGV_ThisAssemblyNamespace>
        <NBGV_ThisAssemblyIncludesPackageVersion>true</NBGV_ThisAssemblyIncludesPackageVersion>
        <GitVersionBaseDirectory>$(MSBuildThisFileDirectory)</GitVersionBaseDirectory>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

        <!-- Test project detection -->
        <IsTestProject Condition="$(MSBuildProjectName.EndsWith('Tests')) or $(MSBuildProjectName.EndsWith('.TestBase'))">true</IsTestProject>
        <IsToolingProject Condition="$(MSBuildProjectName.EndsWith('.Analyzers')) or $(MSBuildProjectName.EndsWith('.CodeFixes')) or $(MSBuildProjectName.EndsWith('.Generators')) or $(MSBuildProjectName.EndsWith('.Logging'))">true</IsToolingProject>

        <!-- Version to use -->
        <AielVersion>0.0.3</AielVersion>
    </PropertyGroup>

    <!-- NuGet metadata (applies to all packable projects) -->
    <PropertyGroup>
        <Title>Two Rivers Aiel</Title>
        <Description>Framework and tools for implementing applications by following best practices in a developer friendly way.</Description>
        <Authors>Doug Wilson</Authors>
        <Company>Two Rivers Information Technology Inc.</Company>
        <Copyright>© Two Rivers Information Technology Inc. All rights reserved.</Copyright>

        <PackageProjectUrl>https://github.com/TwoRiversIT/Aiel</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>logo.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

        <RepositoryUrl>https://github.com/TwoRiversIT/Aiel.git</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <PackageId>$(AssemblyName)</PackageId>
        <ErrorReport>send</ErrorReport>

        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>

        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>

        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <Deterministic>true</Deterministic>

    </PropertyGroup>

    <ItemGroup>
        <Using Include="System" />
        <Using Include="System.Diagnostics.CodeAnalysis" />
        <Using Include="System.Linq" />
    </ItemGroup>

    <!-- NBGV package reference -->
    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.85">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DotNet.ReproducibleBuilds" Version="2.0.5" PrivateAssets="All" />
    </ItemGroup>

    <!-- Analyzers -->
    <ItemGroup>
        <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <!-- Fody weavers -->
    <ItemGroup Condition="'$(IsTestProject)' == 'false'">
        <PackageReference Include="Fody" Version="6.9.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ConfigureAwait.Fody" Version="3.3.2" PrivateAssets='All' />
    </ItemGroup>



    <PropertyGroup Condition="'$(IsTestProject)' == 'false'">
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    </PropertyGroup>

</Project>