<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Testing.Dummies</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <!-- Reference the analyzer and generator project as an analyzer to ensure it is used during compilation of this project. -->
    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Authorization.Analyzers\Aiel.Authorization.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\Aiel.Authorization.Generators\Aiel.Authorization.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <!-- Temporarily disabling analyzers until I figure out which one is crashing the diagnostic runner.
        <ProjectReference Include="..\..\src\Aiel.Framework.Analyzers\Aiel.Framework.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        -->
        <ProjectReference Include="..\..\src\Aiel.Framework.Generators\Aiel.Framework.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\Aiel.Results.Analyzers\Aiel.Results.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\Aiel.Results.Generators\Aiel.Results.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\Aiel.StrongIds.Analyzers\Aiel.StrongIds.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\Aiel.StrongIds.Generators\Aiel.StrongIds.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>        
        <ProjectReference Include="..\..\src\Aiel.Domain\Aiel.Domain.csproj" />
        <ProjectReference Include="..\..\src\Aiel.Testing\Aiel.Testing.csproj" />
    </ItemGroup>

</Project>
