// MIT License
//
// Copyright 2026 Two Rivers Information Technology Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sub-license,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

using Aiel.Roslyn;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Testing;
using System.Collections.Immutable;
using Verify = Microsoft.CodeAnalysis.Testing.AnalyzerVerifier<Aiel.Analyzers.AssemblyAnalyzer, Microsoft.CodeAnalysis.CSharp.Testing.CSharpAnalyzerTest<Aiel.Analyzers.AssemblyAnalyzer, Microsoft.CodeAnalysis.Testing.DefaultVerifier>, Microsoft.CodeAnalysis.Testing.DefaultVerifier>;

namespace Aiel.Analyzers;

public class AssemblyAnalyzerTests
{
    private const String AielStub = """
        namespace Aiel.Dependencies
        {
            public abstract class AielDependencyConfigurator { }
            public abstract class AielApplication : AielDependencyConfigurator { }
        }
        """;

    [Fact]
    public async Task ReportsDiagnostic_WhenNoDependencyPresent()
    {
        const String consumerSource = """
            using System;

            namespace Consumer
            {
                public class SomeType
                {
                    // no AielDependencyConfigurator or AielApplication subclass here
                }
            }
            """;

        var test = new CSharpAnalyzerTest<AssemblyAnalyzer, DefaultVerifier>
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net100,
            TestState =
            {
                Sources = { AielStub, consumerSource }
            }
        };

        // Analyzer reports once per compilation. The test harness names sources:
        // Test0.cs (AielStub) and Test1.cs (consumerSource).
        // The compilation-level code in the analyzer uses the first syntax tree,
        // so we expect the diagnostic on /0/Test0.cs line 1 column 1.
        var expected = Verify.Diagnostic(DiagnosticDescriptors.AIEL00001_RootDependencyRequiredId)
            .WithSpan("/0/Test0.cs", 1, 1, 1, 10)
            .WithArguments("TestProject", 0);

        test.ExpectedDiagnostics.Add(expected);

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task DoesNotReport_WhenCompilationDoesNotReferenceAielCore()
    {
        const String source = """
		namespace Sample;

		public class SomeClass { }
		""";

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: false);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task ReportsDiagnostic_WhenNoRootDependencyTypeIsDefined()
    {
        const String source = """
		using Aiel.Dependencies;

		namespace Sample;

		public abstract class NotRoot : AielDependencyConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: true);

        var diagnostic = Assert.Single(diagnostics);
        Assert.Equal(DiagnosticDescriptors.AIEL00001_RootDependencyRequiredId, diagnostic.Id);
    }

    [Fact]
    public async Task ReportsDiagnostic_WhenOnlyGeneratedSourceTreeIsAvailable()
    {
        const String source = """
        // <auto-generated />
        namespace Sample;

        public class GeneratedType
        {
        }
        """;

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: true);

        var diagnostic = Assert.Single(diagnostics);
        Assert.Equal(DiagnosticDescriptors.AIEL00001_RootDependencyRequiredId, diagnostic.Id);
    }

    [Fact]
    public async Task DoesNotReport_WhenExactlyOneValidAielDependencyTypeExists()
    {
        const String source = """
		using Aiel.Dependencies;

		namespace Sample;

		public sealed class MyRootDependency : AielDependencyConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: true);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task DoesNotReport_WhenExactlyOneValidAielApplicationTypeExists()
    {
        const String source = """
		using Aiel.Dependencies;

		namespace Sample;

		public sealed class MyApplication : AielApplication { }
		""";

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: true);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task ReportsDiagnostic_OnEachCandidate_WhenMultipleRootDependencyTypesExist()
    {
        const String source = """
		using Aiel.Dependencies;

		namespace Sample;

		public sealed class Root1 : AielDependencyConfigurator { }
		public sealed class Root2 : AielDependencyConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: true);

        Assert.Equal(2, diagnostics.Length);
        Assert.All(diagnostics, d => Assert.Equal(DiagnosticDescriptors.AIEL00001_RootDependencyRequiredId, d.Id));
    }

    [Fact]
    public async Task ReportsDiagnostic_OnEachCandidate_WhenAielDependencyAndAielApplicationTypesExist()
    {
        const String source = """
		using Aiel.Dependencies;

		namespace Sample;

		public sealed class Root1 : AielDependencyConfigurator { }
		public sealed class Root2 : AielApplication { }
		""";

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: true);

        Assert.Equal(2, diagnostics.Length);
        Assert.All(diagnostics, d => Assert.Equal(DiagnosticDescriptors.AIEL00001_RootDependencyRequiredId, d.Id));
    }

    [Fact]
    public async Task Ignores_TypesWithoutPublicParameterlessConstructor()
    {
        const String source = """
		using Aiel.Dependencies;

		namespace Sample;

		public sealed class NoDefaultCtor : AielDependencyConfigurator
		{
			public NoDefaultCtor(String name) { }
		}
		""";

        var diagnostics = await AnalyzeAsync(source, referenceAielCore: true);

        var diagnostic = Assert.Single(diagnostics);
        Assert.Equal(DiagnosticDescriptors.AIEL00001_RootDependencyRequiredId, diagnostic.Id);
    }

    private static async Task<ImmutableArray<Diagnostic>> AnalyzeAsync(String source, Boolean referenceAielCore)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(Object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location),
        };

        if (referenceAielCore)
        {
            // Provide a minimal in-memory definition of Aiel.Dependencies.AielDependencyConfigurator
            var coreTree = CSharpSyntaxTree.ParseText(AielStub);
            var coreCompilation = CSharpCompilation.Create(
                "Aiel",
                [coreTree],
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            await using var stream = new MemoryStream();
            var emitResult = coreCompilation.Emit(stream);
            if (!emitResult.Success)
            {
                throw new InvalidOperationException("Failed to emit in-memory Aiel stub for analyzer tests.");
            }

            stream.Position = 0;
            references.Add(MetadataReference.CreateFromImage(stream.ToArray()));
        }

        var compilation = CSharpCompilation.Create(
            "AssemblyAnalyzerUnitTests",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var analyzer = new AssemblyAnalyzer();
        var analyzers = ImmutableArray.Create<DiagnosticAnalyzer>(analyzer);

        var compilationWithAnalyzers = compilation.WithAnalyzers(analyzers);
        return await compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync();
    }
}

