<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Mediator.FluentValidation</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Mediator.Analyzers\Aiel.Mediator.Analyzers.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.Results.Analyzers\Aiel.Results.Analyzers.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.Results.Generators\Aiel.Results.Generators.csproj" OutputItemType="Analyzer" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aiel.Mediator.Abstractions\Aiel.Mediator.Abstractions.csproj" />
    </ItemGroup>

</Project>
