<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace />
		<AssemblyName>Aiel.StrongIds.Analyzers.UnitTests</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		
        <IsToolingTests>true</IsToolingTests>
	</PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\..\src\Aiel.StrongIds\Aiel\StrongIds\IStrongId.cs" Link="Aiel\StrongIds\Stubs\IStrongId.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.StrongIds\Aiel\StrongIds\StrongIdAttribute.cs" Link="Aiel\StrongIds\Stubs\StrongIdAttribute.txt" />
    </ItemGroup>

    <ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.4" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.3.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Aiel.StrongIds.Analyzers\Aiel.StrongIds.Analyzers.csproj" />
		<ProjectReference Include="..\..\src\Aiel.Utilities\Aiel.Utilities.csproj" />
	</ItemGroup>

</Project>
