<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Results.Abstractions</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <Import Project="..\Aiel.Roslyn\Aiel.Roslyn.projitems" Label="Shared" />

    <ItemGroup>
        <None Include="..\Aiel.Results.Analyzers\bin\$(Configuration)\netstandard2.0\Aiel.Results.Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="..\Aiel.Results.Generators\bin\$(Configuration)\netstandard2.0\Aiel.Results.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="Aiel.Results.Abstractions.props" Pack="true" PackagePath="buildTransitive/" Visible="false" />
    </ItemGroup>

    <!-- Reference the analyzer and generator to ensure they are built before this project and available during compilation. -->
    <ItemGroup>
        <ProjectReference Include="..\Aiel.Results.Analyzers\Aiel.Results.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <ProjectReference Include="..\Aiel.Results.Generators\Aiel.Results.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aiel.Framework.Abstractions\Aiel.Framework.Abstractions.csproj" />
    </ItemGroup>

</Project>
