<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Framework.UnitTests.Stubs</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsTestProject>false</IsTestProject>
        <IsToolingTests>true</IsToolingTests>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Aiel\Framework\Stubs\Usings.txt" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Collections\ObservableServiceCollection.cs" Link="Aiel\Framework\Stubs\ObservableServiceCollection.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\AielApplicationConfigurator.cs" Link="Aiel\Framework\Stubs\AielApplicationConfigurator.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\AielDependencyConfigurator.cs" Link="Aiel\Framework\Stubs\AielDependencyConfigurator.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\AielEnvironment.cs" Link="Aiel\Framework\Stubs\AielEnvironment.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\AielFrameworkAbstractions.cs" Link="Aiel\Framework\Stubs\AielFrameworkAbstractions.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\ConfigurationContext.cs" Link="Aiel\Framework\Stubs\ConfigurationContext.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\DependencyContext.cs" Link="Aiel\Framework\Stubs\DependencyContext.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\DependencyDescriptor.cs" Link="Aiel\Framework\Stubs\DependencyDescriptor.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\DependsOnAttribute.cs" Link="Aiel\Framework\Stubs\DependsOnAttribute.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\DisposableBase.cs" Link="Aiel\Framework\Stubs\DisposableBase.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\DisposableExtensions.cs" Link="Aiel\Framework\Stubs\DisposableExtensions.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\IApplicationConfigurator.cs" Link="Aiel\Framework\Stubs\IApplicationConfigurator.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\IApplicationInfo.cs" Link="Aiel\Framework\Stubs\IApplicationInfo.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\IConfigurator.cs" Link="Aiel\Framework\Stubs\IConfigurator.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\IDependencyManager.cs" Link="Aiel\Framework\Stubs\IDependencyManager.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\IInitializer.cs" Link="Aiel\Framework\Stubs\IInitializer.txt" />
        <EmbeddedResource Include="..\..\src\Aiel.Framework.Abstractions\Aiel\Framework\InitializationContext.cs" Link="Aiel\Framework\Stubs\InitializationContext.txt" />
        <EmbeddedResource Include="Aiel\Framework\Stubs\Usings.txt" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Utilities\Aiel.Utilities.csproj" />
    </ItemGroup>

</Project>
