<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace />
		<AssemblyName>Aiel.StrongIds</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<None Include="./README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<!-- Include the analyzer DLL in the NuGet package to ensure it is available and used during compilation of consuming projects. -->
	<ItemGroup>
		<None Include="..\Aiel.StrongIds.Analyzers\bin\$(Configuration)\netstandard2.0\Aiel.StrongIds.Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="..\Aiel.StrongIds.Generators\bin\$(Configuration)\netstandard2.0\Aiel.StrongIds.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="Aiel.StrongIds.props" Pack="true" PackagePath="buildTransitive/" Visible="false" />
	</ItemGroup>

    <!-- Reference the analyzer and generator to ensure they are built before this project and available during compilation. -->
    <ItemGroup>
        <ProjectReference Include="..\Aiel.StrongIds.Analyzers\Aiel.StrongIds.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
        <ProjectReference Include="..\Aiel.StrongIds.Generators\Aiel.StrongIds.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
		<ProjectReference Include="..\Aiel.Framework.Abstractions\Aiel.Framework.Abstractions.csproj" />
	</ItemGroup>

</Project>
