<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Authorization.Abstractions</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Threading" />
        <Using Include="System.Threading.Tasks" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="..\Aiel.Authorization.Analyzers\bin\$(Configuration)\netstandard2.0\Aiel.Authorization.Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="..\Aiel.Authorization.Generators\bin\$(Configuration)\netstandard2.0\Aiel.Authorization.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="Aiel.Authorization.Abstractions.props" Pack="true" PackagePath="buildTransitive/" Visible="false" />
    </ItemGroup>

    <!-- Reference the analyzer and generator project as an analyzer to ensure it is built before this project. -->
    <ItemGroup>
        <ProjectReference Include="..\Aiel.Actions\Aiel.Actions.csproj" />
        <ProjectReference Include="..\Aiel.Authorization.Analyzers\Aiel.Authorization.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
        <ProjectReference Include="..\Aiel.Authorization.Generators\Aiel.Authorization.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
        <ProjectReference Include="..\Aiel.Framework.Abstractions\Aiel.Framework.Abstractions.csproj" />
        <ProjectReference Include="..\Aiel.Results.Abstractions\Aiel.Results.Abstractions.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Aiel.StrongIds\Aiel.StrongIds.csproj" />
        <ProjectReference Include="..\Aiel.StrongIds.Generators\Aiel.StrongIds.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>

</Project>
