<Project Sdk="Microsoft.NET.Sdk">


    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Mediator.FluentValidation.UnitTests</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Mediator.FluentValidation\Aiel.Mediator.FluentValidation.csproj" />
        <ProjectReference Include="..\Aiel.Mediator.UnitTests\Aiel.Mediator.UnitTests.csproj" />
    </ItemGroup>

</Project>
