<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Framework.WebApplication.UnitTests</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Framework.Analyzers\Aiel.Framework.Analyzers.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.Framework.Generators\Aiel.Framework.Generators.csproj" OutputItemType="Analyzer" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Framework.WebApplication\Aiel.Framework.WebApplication.csproj" />
        <ProjectReference Include="..\Aiel.Framework.TestBase\Aiel.Framework.TestBase.csproj" />
    </ItemGroup>

</Project>
