// MIT License
//
// Copyright 2026 Two Rivers Information Technology Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sub-license,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

using Aiel.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using System.Collections.Immutable;
using static Aiel.Framework.Stubs.Stubs;

namespace Aiel.Framework.Analyzers;

public class AssemblyAnalyzerTests
{
    [Fact]
    public async Task DoesNotReport_WhenCompilationDoesNotReferenceAielFramework()
    {
        const String testCode = """
		namespace Sample;

		public class SomeClass { }
		""";

        var diagnostics = await AnalyzeAsync(testCode, referenceAielCore: false);

        diagnostics.Should().HaveCount(0);
    }

    [Fact]
    public async Task DoesNotReport_WhenExactlyOneValidAielApplicationTypeExists()
    {
        const String testCode = """
		using Aiel.Framework;

		namespace Sample;

		public sealed class MyApplication : AielApplicationConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(0);
    }

    [Fact]
    public async Task DoesNotReport_WhenExactlyOneValidAielDependencyTypeExists()
    {
        const String testCode = """
		using Aiel.Framework;

		namespace Sample;

		public sealed class MyRootDependency : AielDependencyConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(0);
    }

    [Fact]
    public async Task Ignores_TypesWithoutPublicParameterlessConstructor()
    {
        const String testCode = """
		using Aiel.Framework;

		namespace Sample;

		public sealed class NoDefaultCtor : AielDependencyConfigurator
		{
			public NoDefaultCtor(String name) { }
		}
		""";

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(1);
        diagnostics[0].Id.Should().Be(DiagnosticRuleIDs.AIEL00001_RootDependencyRequiredId);
    }

    [Fact]
    public async Task ReportsDiagnostic_WhenDependencyIsNotSealed()
    {
        const String testCode = """
            using Aiel.Framework;

            namespace Aiel.Domain;

            [DependsOn(typeof(AielFrameworkAbstractions))]
            public class AielDomainAbstractions : AielDependencyConfigurator;            
            """;

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(1);

        diagnostics[0].Id.Should().Be(DiagnosticRuleIDs.AIEL00020_DependencyIsNotSealedId);
    }

    [Fact]
    public async Task ReportsDiagnostic_WhenNoDependencyPresent()
    {
        const String testCode = """
            using System;

            namespace Consumer
            {
                public class SomeType
                {
                    // no AielDependencyConfigurator or AielApplicationConfigurator subclass here
                }
            }
            """;

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(1);

        diagnostics[0].Id.Should().Be(DiagnosticRuleIDs.AIEL00001_RootDependencyRequiredId);
    }

    [Fact]
    public async Task ReportsDiagnostic_WhenNoRootDependencyTypeIsDefined()
    {
        const String testCode = """
		using Aiel.Framework;

		namespace Sample;

		public abstract class NotRoot : AielDependencyConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(1);
        diagnostics[0].Id.Should().Be(DiagnosticRuleIDs.AIEL00001_RootDependencyRequiredId);
    }

    [Fact]
    public async Task ReportsDiagnostic_WhenOnlyGeneratedSourceTreeIsAvailable()
    {
        const String testCode = """
        // <auto-generated />
        namespace Sample;

        public class GeneratedType
        {
        }
        """;

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(1);
        diagnostics[0].Id.Should().Be(DiagnosticRuleIDs.AIEL00001_RootDependencyRequiredId);
    }

    [Fact]
    public async Task ReportsDiagnostic_OnEachCandidate_WhenMultipleRootDependencyTypesExist()
    {
        const String testCode = """
		using Aiel.Framework;

		namespace Sample;

		public sealed class Root1 : AielDependencyConfigurator { }
		public sealed class Root2 : AielDependencyConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(2);
        diagnostics.Should().AllSatisfy(d => d.Id.Should().Be(DiagnosticRuleIDs.AIEL00001_RootDependencyRequiredId));
    }

    [Fact]
    public async Task ReportsDiagnostic_OnEachCandidate_WhenAielDependencyAndAielApplicationTypesExist()
    {
        const String testCode = """
		using Aiel.Framework;

		namespace Sample;

		public sealed class Root1 : AielDependencyConfigurator { }
		public sealed class Root2 : AielApplicationConfigurator { }
		""";

        var diagnostics = await AnalyzeAsync(testCode);

        diagnostics.Should().HaveCount(2);
        diagnostics.Should().AllSatisfy(d => d.Id.Should().Be(DiagnosticRuleIDs.AIEL00001_RootDependencyRequiredId));
    }

    private static async Task<ImmutableArray<Diagnostic>> AnalyzeAsync(String testCode, Boolean referenceAielCore = true)
    {
        List<SyntaxTree> trees = [CSharpSyntaxTree.ParseText(testCode)];
        if (referenceAielCore)
        {
            foreach (var stub in AielDependencies)
            {
                trees.Add(CSharpSyntaxTree.ParseText(stub));
            }
        }

        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(Object).Assembly.Location),
        };

        var compilation = CSharpCompilation.Create(
            "UnitTests",
            trees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var analyzer = new AssemblyAnalyzer();
        var analyzers = ImmutableArray.Create<DiagnosticAnalyzer>(analyzer);
        var compilationWithAnalyzers = compilation.WithAnalyzers(analyzers);
        return await compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync(TestContext.Current.CancellationToken);
    }
}
