<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Users</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="OpenIddict.Abstractions" Version="7.6.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aiel.Authorization.Abstractions\Aiel.Authorization.Abstractions.csproj" />
        <ProjectReference Include="..\Aiel.Security\Aiel.Security.csproj" />
        <ProjectReference Include="..\Aiel.StrongIds\Aiel.StrongIds.csproj" />
        <ProjectReference Include="..\Aiel.StrongIds.Generators\Aiel.StrongIds.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>

</Project>
