<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Emailing</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aiel.Domain.Shared\Aiel.Domain.Shared.csproj" />
        <ProjectReference Include="..\Aiel.Emailing.Abstractions\Aiel.Emailing.Abstractions.csproj" />
        <ProjectReference Include="..\Aiel.Security\Aiel.Security.csproj" />
    </ItemGroup>

</Project>
