<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.AspNetCore.IntegrationTests.WebApplication</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <StartupObject>Aiel.AspNetCore.Program</StartupObject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Temporarily disabling analyzers until I figure out which one is crashing the diagnostic runner.
        <ProjectReference Include="..\..\src\Aiel.Framework.Analyzers\Aiel.Framework.Analyzers.csproj" OutputItemType="Analyzer" />
        -->
        <ProjectReference Include="..\..\src\Aiel.Framework.Generators\Aiel.Framework.Generators.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.Framework.WebApplication\Aiel.Framework.WebApplication.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.MultiTenancy\Aiel.MultiTenancy.csproj" />
    </ItemGroup>

</Project>
