<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.StrongIds.UnitTests</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>        
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Results.Analyzers\Aiel.Results.Analyzers.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.Results.Generators\Aiel.Results.Generators.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.StrongIds.Analyzers\Aiel.StrongIds.Analyzers.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.StrongIds.Generators\Aiel.StrongIds.Generators.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\src\Aiel.StrongIds\Aiel.StrongIds.csproj" />
    </ItemGroup>

</Project>