<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.91">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
        <!-- Temporarily disabling analyzers until I figure out which one is crashing the diagnostic runner.
        <ProjectReference Include="..\..\src\Aiel.Framework.Analyzers\Aiel.Framework.Analyzers.csproj" OutputItemType="Analyzer" />
        -->
        <ProjectReference Include="..\..\src\Aiel.Framework.Generators\Aiel.Framework.Generators.csproj" OutputItemType="Analyzer" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Framework.WebAssemblyApplication\Aiel.Framework.WebAssemblyApplication.csproj" />
    </ItemGroup>

</Project>
