<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
        <!-- Temporarily disabling analyzers until I figure out which one is crashing the diagnostic runner.
        <ProjectReference Include="..\..\src\Aiel.Results.Analyzers\Aiel.Results.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Pack="false" PrivateAssets="all" />
        -->
        <ProjectReference Include="..\..\src\Aiel.Results.Generators\Aiel.Results.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Pack="false" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Aiel.Actions.Queries\Aiel.Actions.Queries.csproj" />
      <ProjectReference Include="..\..\src\Aiel.Testing\Aiel.Testing.csproj" />
    </ItemGroup>

</Project>
