<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Framework.Abstractions</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\Aiel.Framework.Analyzers\bin\$(Configuration)\netstandard2.0\Aiel.Framework.Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="..\Aiel.Framework.Generators\bin\$(Configuration)\netstandard2.0\Aiel.Framework.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="Aiel.Framework.Abstractions.props" Pack="true" PackagePath="buildTransitive/" Visible="false" />
    </ItemGroup>

    <!-- Reference the analyzer and generator projects as an analyzer to ensure they are built before this project. -->
    <ItemGroup>
        <ProjectReference Include="..\Aiel.Framework.Analyzers\Aiel.Framework.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
        <ProjectReference Include="..\Aiel.Framework.Generators\Aiel.Framework.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Aiel.Utilities\Aiel.Utilities.csproj" />
    </ItemGroup>

</Project>
