<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>Aiel.Results.Fixtures</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <!-- Temporarily disabled until the analyzer is fixed to not crash the Diagnostic Analyzer Runner.
        <ProjectReference Include="..\..\src\Aiel.Logging.Analyzers\Aiel.Logging.Analyzers.csproj" OutputItemType="Analyzer" />
        -->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Aiel.Results\Aiel.Results.csproj" />
        <ProjectReference Include="..\..\src\Aiel.Testing\Aiel.Testing.csproj" />
    </ItemGroup>

</Project>
